### ISSUE TITLE
DK_PLUGIN_PATH flatpak env points to the wrong directory

### ISSUE THREAD

**Issue by sobczyk** [flathub/org.kde.digikam#138]
flatpak for version 8.5.0
the variable is:
`DK_PLUGIN_PATH=/app/lib64/qt5/plugins/digikam`
the variable should be:
`DK_PLUGIN_PATH=/app/lib64/qt6/plugins/digikam`

Without it the application can't open any photos, only thumbnails work.

**Comment by tsdgeos** [comment]
It points to /app/lib/plugins/digikam that is where the plugins are. 

Can you paste your

flatpak info  org.kde.digikam 

?

**Comment by sobczyk** [comment]
```
digiKam - Photo Management Program

          ID: org.kde.digikam
         Ref: app/org.kde.digikam/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 8.5.0
     License: GPL-2.0+
      Origin: fedora
  Collection:
Installation: system
   Installed: 718.8?MB
     Runtime: org.fedoraproject.KDE6Platform/x86_64/f41
         Sdk: org.fedoraproject.KDE6Sdk/x86_64/f41

      Commit: 157b64e6fc06b679112ab131b59fcfbafa49d5208b04ac0f5d97b4b7233d2c0b
     Subject: Export org.kde.digikam
        Date: 2024-11-25 04:19:54 +0000
      Alt-id: b2f5e8ccf81c709d1f20008153edafce9f1a2675cb7b103a196c0ab4b278ce50
```
